<?php

/**
 * @file
 * Provides a way to disable system css files
 */

/**
 * Implements hook_menu()
 */

function unsettler_menu() {
	$items['admin/config/development/unsettler'] = array(
		'title' => 'Unset core CSS files',
		'description' => t('Enable or disable core Drupal CSS files.'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('unsettler_form'),
		'access arguments' => array('administer core css'),
		'type' => MENU_NORMAL_ITEM,
	);
	
	return $items;
}

function unsettler_form($form, &$form_state) {

	// system.base.css
	$form['unsettler_base_checkbox'] = array(
		'#type' => 'checkbox',
		'#title' => 'disable system.base.css',
		'#default_value' => variable_get('unsettler_base_checkbox', 0),
	);
	
	// system.menus.css
	$form['unsettler_menu_checkbox'] = array(
		'#type' => 'checkbox',
		'#title' => 'disable system.menus.css',
		'#default_value' => variable_get('unsettler_menu_checkbox', 0),
	);
	
	// system.messages.css
	$form['unsettler_messages_checkbox'] = array(
		'#type' => 'checkbox',
		'#title' => 'disable system.messages.css',
		'#default_value' => variable_get('unsettler_messages_checkbox', 0),
	);
	
	// system.theme.css
	$form['unsettler_theme_checkbox'] = array(
		'#type' => 'checkbox',
		'#title' => 'disable system.theme.css',
		'#default_value' => variable_get('unsettler_theme_checkbox', 0),
	);
	
	return system_settings_form($form);
}

function unsettler_css_alter(&$css) {
	if (variable_get('unsettler_base_checkbox', 0) == 1) {
		unset($css[drupal_get_path('module', 'system') . '/system.base.css']);	
	}
	if (variable_get('unsettler_menu_checkbox', 0) == 1) {
		unset($css[drupal_get_path('module', 'system') . '/system.menus.css']);	
	}
	if (variable_get('unsettler_messages_checkbox', 0) == 1) {
		unset($css[drupal_get_path('module', 'system') . '/system.messages.css']);	
	}
	if (variable_get('unsettler_theme_checkbox', 0) == 1) {
		unset($css[drupal_get_path('module', 'system') . '/system.theme.css']);	
	}
}